export const newReleases = [
  {
    id: "1",
    title: "Find a Sponsor",
    author: "Sylvia Ann Hewlett",
    image: "https://picsum.photos/200/300?3",
    tag: "Non-Fiction",
  },
  {
    id: "2",
    title: "Sherlock Holmes",
    author: "Arthur Conan Doyle",
    image: "https://picsum.photos/200/300?4",
    tag: "Fiction",
  },
  {
    id: "3",
    title: "The Creative Act",
    author: "Rick Rubin",
    image: "https://picsum.photos/200/300?5",
    tag: "Art",
  },
  {
    id: "4",
    title: "Project Hail Mary",
    author: "Andy Weir",
    image: "https://picsum.photos/200/300?6",
    tag: "Science Fiction",
  },
  {
    id: "5",
    title: "Lessons in Chemistry",
    author: "Bonnie Garmus",
    image: "https://picsum.photos/200/300?7",
    tag: "Fiction",
  },
  {
    id: "6",
    title: "The Light We Carry",
    author: "Michelle Obama",
    image: "https://picsum.photos/200/300?8",
    tag: "Memoir",
  },
  {
    id: "7",
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    image: "https://picsum.photos/200/300?9",
    tag: "Fiction",
  },
];